"""empty message

Revision ID: 017f58542625
Revises: 6883a8b318e5
Create Date: 2026-06-30 19:26:01.121941

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "017f58542625"
down_revision: Union[str, Sequence[str], None] = "6883a8b318e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
