"""add_relationships

Revision ID: 0c064b22e96f
Revises: 1275decebdfa
Create Date: 2026-06-28 01:57:30.964340

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0c064b22e96f"
down_revision: Union[str, Sequence[str], None] = "1275decebdfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
