"""Fix chat message thread back_populates relationship

Revision ID: 342e08073927
Revises: cdcb39ab290f
Create Date: 2026-07-20 16:19:53.278911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342e08073927'
down_revision: Union[str, Sequence[str], None] = 'cdcb39ab290f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
