"""empty message

Revision ID: 6883a8b318e5
Revises: 0c064b22e96f
Create Date: 2026-06-30 19:22:49.265539

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6883a8b318e5"
down_revision: Union[str, Sequence[str], None] = "0c064b22e96f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
