"""Add message_type and metadata to chat_messages

Revision ID: 6dd8622f24aa
Revises: ce2d26864b9d
Create Date: 2026-07-20 15:39:05.219776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dd8622f24aa'
down_revision: Union[str, Sequence[str], None] = 'ce2d26864b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('chat_messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'text'::character varying"))
    # ### end Alembic commands ###
