"""add resume downloads table

Revision ID: 9f8d0b49f332
Revises: 8185c41af0d4
Create Date: 2026-07-02 23:29:35.681604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8d0b49f332'
down_revision: Union[str, Sequence[str], None] = '8185c41af0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_submission_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_message_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_message_id'], ['contact_messages.id'], name=op.f('fk_contact_submission_events_contact_message_id_contact_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_submission_events'))
    )
    op.create_table('resume_downloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('visitor_name', sa.String(), nullable=True),
    sa.Column('visitor_email', sa.String(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_downloads_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_downloads'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_downloads')
    op.drop_table('contact_submission_events')
    # ### end Alembic commands ###
