"""Add thread relationship to ChatMessage

Revision ID: cdcb39ab290f
Revises: 6dd8622f24aa
Create Date: 2026-07-20 16:16:11.546725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdcb39ab290f'
down_revision: Union[str, Sequence[str], None] = '6dd8622f24aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
