"""add chat events table

Revision ID: f8e21922f42e
Revises: 9f8d0b49f332
Create Date: 2026-07-02 23:42:31.535760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e21922f42e'
down_revision: Union[str, Sequence[str], None] = '9f8d0b49f332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('thread_created', 'message_sent', 'response_generated', name='chat_event_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], name=op.f('fk_chat_events_thread_id_chat_threads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['chat_visitors.id'], name=op.f('fk_chat_events_visitor_id_chat_visitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_events')
    # ### end Alembic commands ###
