"""initial

Revision ID: fd2c5603cd8d
Revises:
Create Date: 2026-06-27 17:55:16.857029

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fd2c5603cd8d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
